---
spring:
 profiles: default
 cloud:
  config:
   server:
    git:
     uri: https://github.com/gunaskr/splitter
     searchPaths: application-configuration
 application:
  name: config-server
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/