/**
 * splitter transaction-management REST API
 * This is the description of the splitter transaction-management REST API endpoints.
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Category { 
    createdAt?: string;
    icon?: string;
    id?: string;
    type?: Category.TypeEnum;
    updatedAt?: string;
}
export namespace Category {
    export type TypeEnum = 'FOOD' | 'TRAVEL';
    export const TypeEnum = {
        FOOD: 'FOOD' as TypeEnum,
        TRAVEL: 'TRAVEL' as TypeEnum
    };
}
