/**
 * splitter transaction-management REST API
 * This is the description of the splitter transaction-management REST API endpoints.
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionVO } from './transactionVO';


export interface EventVO { 
    amountSpent?: number;
    category?: EventVO.CategoryEnum;
    id?: string;
    name?: string;
    transactions?: Array<TransactionVO>;
    userId?: string;
}
export namespace EventVO {
    export type CategoryEnum = 'FOOD' | 'TRAVEL';
    export const CategoryEnum = {
        FOOD: 'FOOD' as CategoryEnum,
        TRAVEL: 'TRAVEL' as CategoryEnum
    };
}
