/**
 * splitter transaction-management REST API
 * This is the description of the splitter transaction-management REST API endpoints.
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionVO { 
    amount?: number;
    fromUserId?: string;
    id?: string;
    toUserId?: string;
}
