/**
 * splitter transaction-management REST API
 * This is the description of the splitter transaction-management REST API endpoints.
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { EventVO } from '../model/eventVO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EventControllerService {

    protected basePath = 'https://localhost:8090/transaction-management';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createEvent
     * 
     * @param eventRequest eventRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createEventUsingPOST(eventRequest: EventVO, observe?: 'body', reportProgress?: boolean): Observable<EventVO>;
    public createEventUsingPOST(eventRequest: EventVO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventVO>>;
    public createEventUsingPOST(eventRequest: EventVO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventVO>>;
    public createEventUsingPOST(eventRequest: EventVO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (eventRequest === null || eventRequest === undefined) {
            throw new Error('Required parameter eventRequest was null or undefined when calling createEventUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (x-auth-token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["x-auth-token"]) {
            headers = headers.set('x-auth-token', this.configuration.apiKeys["x-auth-token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<EventVO>(`${this.basePath}/api/event`,
            eventRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * filterEvents
     * 
     * @param fromUserId fromUserId
     * @param toUserId toUserId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public filterEventsUsingGET(fromUserId?: string, toUserId?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<EventVO>>;
    public filterEventsUsingGET(fromUserId?: string, toUserId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EventVO>>>;
    public filterEventsUsingGET(fromUserId?: string, toUserId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EventVO>>>;
    public filterEventsUsingGET(fromUserId?: string, toUserId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fromUserId !== undefined && fromUserId !== null) {
            queryParameters = queryParameters.set('fromUserId', <any>fromUserId);
        }
        if (toUserId !== undefined && toUserId !== null) {
            queryParameters = queryParameters.set('toUserId', <any>toUserId);
        }

        let headers = this.defaultHeaders;

        // authentication (x-auth-token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["x-auth-token"]) {
            headers = headers.set('x-auth-token', this.configuration.apiKeys["x-auth-token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<EventVO>>(`${this.basePath}/api/event`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findEventById
     * 
     * @param eventId eventId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findEventByIdUsingGET(eventId: string, observe?: 'body', reportProgress?: boolean): Observable<EventVO>;
    public findEventByIdUsingGET(eventId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventVO>>;
    public findEventByIdUsingGET(eventId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventVO>>;
    public findEventByIdUsingGET(eventId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (eventId === null || eventId === undefined) {
            throw new Error('Required parameter eventId was null or undefined when calling findEventByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (x-auth-token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["x-auth-token"]) {
            headers = headers.set('x-auth-token', this.configuration.apiKeys["x-auth-token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventVO>(`${this.basePath}/api/event/${encodeURIComponent(String(eventId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
